Repository planetarium/NineChronicles.LiveAssets, pull requests merged in 2022-12, with the labels that each got.

#5 Add new format of data
  Assets/Images/Notice/InviteFriend.png
  Assets/Images/Notice/MonsterCollection.png
  Assets/Json/Event.json
  Assets/Json/TextNotice.json
Labels: Small

#6 Update rune event banner (v100340)
  Assets/Images/Banner/Banner_1.png
  Assets/Images/Banner/Banner_2.png
  Assets/Images/Banner/Banner_3.png
  Assets/Images/Banner/Banner_4.png
  Assets/Images/Banner/_Banner_1.png
  Assets/Images/Banner/_Banner_GrandFinaleVoting.png
  Assets/Images/Banner/__Banner_1.png
  Assets/Images/Banner/___Banner_1.png
  Assets/Images/Notice/Banner_Main.png
  Assets/Images/Notice/RuneUpgrade.png
  Assets/Json/Banner.json
  Assets/Json/Notice.json
Labels: Small

#7 Change banner resources
  Assets/Images/Banner/Banner_1.png
  Assets/Images/Notice/Banner_Main.png
Labels: No Changes

#9 Update 221215 for PFP Staking
  Assets/Images/Banner/Banner_3.png
  Assets/Images/Banner/Banner_4.png
  Assets/Images/Banner/dcc_staking.png
  Assets/Images/Notice/InviteFriend.png
  Assets/Images/Notice/MonsterCollection.png
  Assets/Images/Notice/dcc_staking.png
  Assets/Images/Notice/dcc_staking_600_420.png
  Assets/Images/Notice/rune_open.png
  Assets/Json/Banner.json
  Assets/Json/Event.json
  Assets/Json/Notice.json
Labels: Extra Small

#10 Update release note for v100350-1
  Assets/Json/TextNotice.json
Labels: Extra Small

#11 Bug fix about datetime and add winter event
  Assets/Images/Banner/world_horizon.png
  Assets/Images/Notice/world_horizon.png
  Assets/Json/Event.json
Labels: Extra Small

#12 Use DateTime for v100350-2
  Assets/Json/Event.json
  Assets/Json/TextNotice.json
Labels: Extra Small
