Repository planetarium/NineChronicles.LiveAssets, pull requests merged in 2023-11, with the labels that each got.

#77 Update clo-app-ver-0-0-1-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-0-0-1-aos.json
Labels: Extra Small

#78 Update clo-app-ver-0-0-1-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-0-0-1-aos.json
Labels: Extra Small

#79 Update clo-app-ver-0-0-1-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-0-0-1-aos.json
Labels: Extra Small

#81 change 71.0.0 clo to mainnet
  Assets/Json/CloForAppVersion/clo-app-ver-71-0-0-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-71-0-0-ios.json
Labels: Small

#83 Update clo-app-ver-80-0-0-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-80-0-0-aos.json
Labels: Extra Small

#85 Add clo for 90.0.15
  Assets/Json/CloForAppVersion/clo-app-ver-90-0-15-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-90-0-15-ios.json
Labels: enhancement, Extra Small

#86 chore 90.0.16
  Assets/Json/CloForAppVersion/clo-app-ver-90-0-16-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-90-0-16-ios.json
Labels: Extra Small

#87 Create clo-app-ver-90-0-17.json
  Assets/Json/CloForAppVersion/clo-app-ver-90-0-17-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-90-0-17-ios.json
Labels: Extra Small

#89 Prepare/v200110
  Assets/Images/Banner/Banner_Event53.png
  Assets/Images/Banner/Banner_Event53_JP.png
  Assets/Images/Banner/Banner_Event53_KR.png
  Assets/Images/Banner/Banner_Event54.png
  Assets/Images/Banner/Banner_Event54_JP.png
  Assets/Images/Banner/Banner_Event54_KR.png
  Assets/Images/Banner/Banner_Event55.png
  Assets/Images/Banner/Banner_Event55_JP.png
  Assets/Images/Banner/Banner_Event55_KR.png
  Assets/Images/Banner/Banner_Event56.png
  Assets/Images/Banner/Banner_Event56_JP.png
  Assets/Images/Banner/Banner_Event56_KR.png
  Assets/Images/Banner/Banner_Event57.png
  Assets/Images/Banner/Banner_Event57_JP.png
  Assets/Images/Banner/Banner_Event57_KR.png
  Assets/Images/Notice/Main_Event53.png
  Assets/Images/Notice/Main_Event53_JP.png
  Assets/Images/Notice/Main_Event53_KR.png
  Assets/Images/Notice/Main_Event54.png
  Assets/Images/Notice/Main_Event54_JP.png
  Assets/Images/Notice/Main_Event54_KR.png
  Assets/Images/Notice/Main_Event55.png
  Assets/Images/Notice/Main_Event55_JP.png
  Assets/Images/Notice/Main_Event55_KR.png
  Assets/Images/Notice/Main_Event56.png
  Assets/Images/Notice/Main_Event56_JP.png
  Assets/Images/Notice/Main_Event56_KR.png
  Assets/Images/Notice/Main_Event57.png
  Assets/Images/Notice/Main_Event57_JP.png
  Assets/Images/Notice/Main_Event57_KR.png
  Assets/Json/CloForAppVersion/clo-app-ver-90-0-24-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-90-0-24-ios.json
  Assets/Json/Event.json
  Assets/Json/TextNotice.json
  Assets/Json/TextNotice_JP.json
  Assets/Json/TextNotice_KR.json
Labels: Medium

#90 231124 - black friday and heimdall arena event
  Assets/Images/Banner/BF.png
  Assets/Images/Banner/BF_JP.png
  Assets/Images/Banner/BF_KR.png
  Assets/Images/Banner/h-arena.png
  Assets/Images/Banner/h-arena_JP.png
  Assets/Images/Banner/h-arena_KR.png
  Assets/Images/Notice/BF.png
  Assets/Images/Notice/BF_JP.png
  Assets/Images/Notice/BF_KR.png
  Assets/Images/Notice/h-arena.png
  Assets/Images/Notice/h-arena_JP.png
  Assets/Images/Notice/h-arena_KR.png
  Assets/Json/Event.json
Labels: Extra Small
