Repository planetarium/NineChronicles.LiveAssets, pull requests merged in 2023-12, with the labels that each got.

#93 NewBannerAdd - MonsterCollectionRewardIncrease
  Assets/Images/Banner/MonsterCollectionRewardIncreaseBanner.png
  Assets/Images/Banner/MonsterCollectionRewardIncreaseBanner_JP.png
  Assets/Images/Banner/MonsterCollectionRewardIncreaseBanner_KR.png
  Assets/Images/Notice/MonsterCollectionRewardIncrease.png
  Assets/Images/Notice/MonsterCollectionRewardIncrease_JP.png
  Assets/Images/Notice/MonsterCollectionRewardIncrease_KR.png
  Assets/Json/Event.json
Labels: Extra Small

#94 231207
  Assets/Images/Banner/GoldenHourglass.png
  Assets/Images/Banner/GoldenHourglass_JP.png
  Assets/Images/Banner/GoldenHourglass_KR.png
  Assets/Images/Notice/GoldenHourglass.png
  Assets/Images/Notice/GoldenHourglass_JP.png
  Assets/Images/Notice/GoldenHourglass_KR.png
  Assets/Json/CloForAppVersion/clo-app-ver-90-2-7-ios.json
  Assets/Json/CloForAppVersion/clo-app-ver-90-3-1-ios.json
  Assets/Json/CloForAppVersion/clo-app-ver-90-3-2-ios.json
  Assets/Json/Event.json
Labels: Extra Small

#95 change 100.0.4 clo to mainnet
  Assets/Json/CloForAppVersion/clo-app-ver-100-0-4-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-100-0-4-ios.json
Labels: Extra Small

#96 remove old clo.json for v200120
  Assets/Json/CloForAppVersion/clo-app-ver-100-0-0-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-100-0-0-ios.json
  Assets/Json/CloForAppVersion/clo-app-ver-100-0-1-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-100-0-1-ios.json
  Assets/Json/CloForAppVersion/clo-app-ver-100-0-2-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-100-0-2-ios.json
  Assets/Json/CloForAppVersion/clo-app-ver-90-3-1-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-90-3-2-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-90-3-3-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-90-3-3-ios.json
  Assets/Json/CloForAppVersion/clo-app-ver-90-4-0-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-90-4-0-ios.json
Labels: Medium

#98 231213
  Assets/Images/Banner/NewRunes.png
  Assets/Images/Banner/NewRunes_JP.png
  Assets/Images/Banner/NewRunes_KR.png
  Assets/Images/Banner/SpecialPromo.png
  Assets/Images/Banner/SpecialPromo_JP.png
  Assets/Images/Banner/SpecialPromo_KR.png
  Assets/Images/Banner/VoucherEvent.png
  Assets/Images/Banner/VoucherEvent_JP.png
  Assets/Images/Banner/VoucherEvent_KR.png
  Assets/Images/Notice/NewRunes.png
  Assets/Images/Notice/NewRunes_JP.png
  Assets/Images/Notice/NewRunes_KR.png
  Assets/Images/Notice/SpecialPromo.png
  Assets/Images/Notice/SpecialPromo_JP.png
  Assets/Images/Notice/SpecialPromo_KR.png
  Assets/Images/Notice/VoucherEvent.png
  Assets/Images/Notice/VoucherEvent_JP.png
  Assets/Images/Notice/VoucherEvent_KR.png
  Assets/Json/Event.json
Labels: Extra Small

#97 add ci: auto tagging about `Release`
  .github/workflows/tag-commit-workflow.yml
Labels: Extra Small

#99 V200130
  Assets/Json/CloForAppVersion/clo-app-ver-100-0-3-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-100-0-3-ios.json
  Assets/Json/CloForAppVersion/clo-app-ver-100-0-4-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-100-0-4-ios.json
  Assets/Json/CloForAppVersion/clo-app-ver-110-0-1-aos.json
  Assets/Json/CloForAppVersion/clo-app-ver-110-0-1-ios.json
Labels: Small

#100 add event about christmas...
  Assets/Images/Banner/Christmas.png
  Assets/Images/Banner/Christmas_JP.png
  Assets/Images/Banner/Christmas_KR.png
  Assets/Images/Banner/eventdungeon_patrolreward.png
  Assets/Images/Banner/eventdungeon_patrolreward_JP.png
  Assets/Images/Banner/eventdungeon_patrolreward_KR.png
  Assets/Images/Banner/heimdall_worldboss.png
  Assets/Images/Banner/heimdall_worldboss_JP.png
  Assets/Images/Banner/heimdall_worldboss_KR.png
  Assets/Images/Notice/Christmas.png
  Assets/Images/Notice/Christmas_JP.png
  Assets/Images/Notice/Christmas_KR.png
  Assets/Images/Notice/eventdungeon_patrolreward.png
  Assets/Images/Notice/eventdungeon_patrolreward_JP.png
  Assets/Images/Notice/eventdungeon_patrolreward_KR.png
  Assets/Images/Notice/heimdall_worldboss.png
  Assets/Images/Notice/heimdall_worldboss_JP.png
  Assets/Images/Notice/heimdall_worldboss_KR.png
  Assets/Json/Event.json
Labels: Extra Small

#101 Add adieu event banner
  Assets/Images/Banner/233Adieu2023.png
  Assets/Images/Banner/233Adieu2023_JP.png
  Assets/Images/Banner/233Adieu2023_KR.png
  Assets/Images/Notice/600Adieu2023.png
  Assets/Images/Notice/600Adieu2023_JP.png
  Assets/Images/Notice/600Adieu2023_KR.png
  Assets/Json/Event.json
Labels: enhancement, Small

#102 seasonpass2 eventbanner updated
  Assets/Images/Banner/233Season2.png
  Assets/Images/Banner/233Season2_JP.png
  Assets/Images/Banner/233Season2_KR.png
  Assets/Images/Notice/600Season2.png
  Assets/Images/Notice/600Season2_JP.png
  Assets/Images/Notice/600Season2_KR.png
  Assets/Json/Event.json
Labels: Extra Small
